name: gym_supplements_app
description: A Flutter app for a Gym Supplements store.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # Compatible with >=3.35.6 stable
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  crypto: ^3.0.5  # For password hashing
  args: ^2.5.0
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # No assets needed